{{- if .Values.accounting_exporter.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: accounting-exporter
  name: accounting-exporter-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
string:
  ca.pem: {{ required ".Values.accounting_exporter.accounting_api.ca is required" (b64enc .Values.accounting_exporter.accounting_api.ca) }}
  client.pem: {{ required ".Values.accounting_exporter.accounting_api.cert is required" (b64enc .Values.accounting_exporter.accounting_api.cert) }}
  client-key.pem: {{ required ".Values.accounting_exporter.accounting_api.certkey is required" (b64enc .Values.accounting_exporter.accounting_api.certkey) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: accounting-exporter
spec:
  selector:
    matchLabels:
      k8s-app: accounting-exporter
  template:
    metadata:
      labels:
        k8s-app: accounting-exporter
        app: accounting-exporter
        networking.gardener.cloud/from-prometheus: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: {{ index .Values.images "accounting-exporter" }}
        imagePullPolicy: Always
        name: accounting-exporter
        env:
        - name: KUBE_COUNTER_PARTITION
          value: {{ .Values.accounting_exporter.enrichments.partition_id }}
        - name: KUBE_COUNTER_TENANT
          value: {{ .Values.accounting_exporter.enrichments.tenant }}
        - name: KUBE_COUNTER_PROJECT_ID
          value: {{ .Values.accounting_exporter.enrichments.project_id }}
        - name: KUBE_COUNTER_CLUSTER_ID
          value: {{ .Values.accounting_exporter.enrichments.cluster_id }}
        - name: KUBE_COUNTER_CLUSTER_NAME
          value: {{ .Values.accounting_exporter.enrichments.cluster_name }}
        - name: KUBE_COUNTER_KUBECONFIG
          value: /var/lib/accounting-exporter/kubeconfig
        - name: KUBE_COUNTER_ACCOUNTING_API_HOSTNAME
          value: {{ .Values.accounting_exporter.accounting_api.hostname }}
        - name: KUBE_COUNTER_ACCOUNTING_API_PORT
          value: "{{ .Values.accounting_exporter.accounting_api.port }}"
        volumeMounts:
        - name: accounting-exporter
          mountPath: /var/lib/accounting-exporter
        - mountPath: /certs
          name: certs
      restartPolicy: Always
      volumes:
      - name: accounting-exporter
        secret:
          secretName: accounting-exporter
      - name: certs
        secret:
          secretName: accounting-exporter-tls
{{- end }}
