---
images:
    droptailer: image-repository:image-tag
    metallb-speaker: image-repository:image-tag
    metallb-controller: image-repository:image-tag

firewall:
    interval: 10s
    machineNetworks: []
    internalPrefixes: []
    rateLimits: []
    egressRules: []

firewallSignature: ""

accountingExporter:
    enabled: false

groupRolebindingController:
    enabled: false

limitValidatingWebhook:
    enabled: false
    ca: ABCDEF
    url: https://replace-this-webhook/validate
