replicas: 1
kubernetesVersion: 1.7.5
projectID: project-id
partitionID: partition-id
networkID: network-id
podNetwork: 192.168.0.0/16
environment: []
additionalParameters: []
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images: 
  metalccm: image-repository:image-tag
  authn-webhook: image-repository:image-tag
  group-rolebinding-controller: image-repository:image-tag
  accounting-exporter: image-repository:image-tag
  limit-validating-webhook: image-repository:image-tag

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 300Mi

#
# group-rolebinding-controller
#
grprb_clustername: clustername

#
# authn webhook
#
authn_tenant: someTenant
authn_clustername: projectID

authn_oidcIssuerUrl: https://tokenissuer/dex
authn_oidcIssuerClientId: myClientId
authn_providerTenant: providerTenant

authn_listen_port: 443
authn_debug: true

#
# accounting-exporter
#
accounting_exporter:
  enabled: true
  enrichments:
    project_id: project-id
    partition_id: partition-id
    tenant: someTenant
    cluster_id: 123123
    cluster_name: clustername
  accounting_api:
    hostname: hostname
    port: 9000
    ca: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    certkey: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY----- 

#
# limit-validating-webhook
#
lvw_validate: false
